Vagrant.configure("2") do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.provision :shell, path: "vagrant/install-docker.sh"
  config.vm.provision :shell, path: "vagrant/bootstrap.sh"
end
